# Generated by Django 2.2.1 on 2019-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_cooking',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='cooking',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
