# Generated by Django 2.2.1 on 2019-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='date_birth',
            field=models.DateField(verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
