# Generated by Django 2.2.1 on 2019-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190523_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='', verbose_name='avatar')),
            ],
        ),
    ]
