# Generated by Django 2.2.2 on 2019-06-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='t_img',
        ),
    ]
